Instructions
Dungeons & Dragons is a tabletop role-playing game where players create characters and embark on adventures in a fantasy world. 🧝🏽‍♀️

Here's a DataFrame named characters that holds info on 10 D&D heroes.

Practice selecting individual columns:

Select only the name column and store it in a variable called character_names. Then print the type of this variable. What do you get?
Select the name, level, hp columns and store them in a variable called basic_stats.
Select all columns except alignment and store that in a variable called removed_alignment.

In [1]:
import pandas as pd

In [2]:
# D&D characters data
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}

In [3]:
characters = pd.DataFrame(characters_data)

In [4]:
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [5]:
character_names = characters['name']

In [6]:
character_names

0     Thorne
1      Elira
2       Glim
3       Brug
4        Nyx
5       Kael
6       Mira
7     Drogan
8       Zara
9    Fenwick
Name: name, dtype: object

In [17]:
print(type(characters).__name__)
print(type(characters['name']).__name__)

DataFrame
Series

In [20]:
basic_stats = characters[['name', 'level', 'hp']]

In [21]:
basic_stats

      name  level  hp
0   Thorne      5  42
1    Elira      3  28
2     Glim      4  33
3     Brug      2  25
4      Nyx      6  48
5     Kael      7  56
6     Mira      3  30
7   Drogan      5  44
8     Zara      4  36
9  Fenwick      2  24

In [23]:
removed_alignment = characters.drop('alignment', axis=1)

In [24]:
removed_alignment

      name        race      class  level  hp
0   Thorne         Elf     Ranger      5  42
1    Elira       Human     Cleric      3  28
2     Glim       Gnome     Wizard      4  33
3     Brug    Half-Orc  Barbarian      2  25
4      Nyx    Tiefling      Rogue      6  48
5     Kael  Dragonborn    Paladin      7  56
6     Mira    Halfling       Bard      3  30
7   Drogan       Dwarf    Fighter      5  44
8     Zara     Aasimar   Sorcerer      4  36
9  Fenwick      Goblin    Warlock      2  24