Instructions
First things first, import pandas at the top of the file.

Then, create a DataFrame named contacts containing information about your friends, family, or fictional characters. Your DataFrame should have at least 3 columns and 4 rows.

Feel free to be creative about what columns to include. If you need inspiration, you could consider columns like name, age, phone_number, astrological_sign. 💫

For example:

name	age	phone_number	astrological_sign
Bart	10	939-555-0113	Taurus
Lisa	8	939-555-0114	Virgo
Homer	39	939-555-0115	Taurus
Marge	36	939-555-0116	Pisces
Create the DataFrame using either the dictionary method or the list-of-lists method.

Don't forget to display the table after creating it!

In [4]:
import pandas as pd

In [11]:
contacts = {'name': ['Bart', 'Lisa', 'Homer', 'Marge'],
            'age': [10,8,39,36],
            'phone_number': [9395550113, 9395550114, 9395550115, 9395550116],
            'astrological_sign': ['Taurus', 'Virgo', 'Taurus', 'Pisces']}

In [12]:
df = pd.DataFrame(contacts)

In [13]:
df

    name  age  phone_number astrological_sign
0   Bart   10    9395550113            Taurus
1   Lisa    8    9395550114             Virgo
2  Homer   39    9395550115            Taurus
3  Marge   36    9395550116            Pisces

In [14]:
print(df)

    name  age  phone_number astrological_sign
0   Bart   10    9395550113            Taurus
1   Lisa    8    9395550114             Virgo
2  Homer   39    9395550115            Taurus
3  Marge   36    9395550116            Pisces

In [15]:
data = [
  ['Brooklyn', 'US', 2646000],
  ['Seoul', 'South Korea', 9411000],
  ['Barcelona', 'Spain', 1636000],
  ['Mexico City', 'Mexico', 9209944]
]

In [16]:
df1 = pd.DataFrame(data, columns=['City', 'Country', 'Population'])

In [21]:
df1.describe(include = 'all')

            City Country    Population
count          4       4  4.000000e+00
unique         4       4           NaN
top     Brooklyn      US           NaN
freq           1       1           NaN
mean         NaN     NaN  5.725736e+06
std          NaN     NaN  4.160593e+06
min          NaN     NaN  1.636000e+06
25%          NaN     NaN  2.393500e+06
50%          NaN     NaN  5.927972e+06
75%          NaN     NaN  9.260208e+06
max          NaN     NaN  9.411000e+06

In [22]:
print(df1.describe(include = 'all'))

            City Country    Population
count          4       4  4.000000e+00
unique         4       4           NaN
top     Brooklyn      US           NaN
freq           1       1           NaN
mean         NaN     NaN  5.725736e+06
std          NaN     NaN  4.160593e+06
min          NaN     NaN  1.636000e+06
25%          NaN     NaN  2.393500e+06
50%          NaN     NaN  5.927972e+06
75%          NaN     NaN  9.260208e+06
max          NaN     NaN  9.411000e+06