Instructions
We all love hospital shows – Grey's Anatomy, House, Scrubs, and the more recent The Pitt.

Here's a dataset of emergency department patient intake records inspired The Pitt. 🏥

It reflects the fast-paced, high-pressure environment of a hospital emergency department, where data is often entered quickly and under stress. As a result, it contains common real-world quality issues such as missing values, duplicate records, inconsistent text formatting, and incorrect data types.

Your task is to clean the dataset so it is suitable for analysis. However, there is no single "correct" way to do this; the specific approach is up to you!

For example, you might:

Remove duplicate records if they represent system logging errors.
Standardize medical categories (e.g., critical, CRITICAL, Critical).
Convert numeric fields into proper numeric types.
Fill or remove missing values depending on clinical relevance.
Normalize text fields for consistency across shifts.
You got this, doc! 🧑‍⚕️

In [44]:
import pandas as pd

patients = pd.DataFrame({
  'patient_id': [
    'PT-2001', 'PT-2001', 'PT-2002', 'PT-2003', 
    'PT-2004', 'PT-2005', 'PT-2006', 'PT-2006', 
    'PT-2007', 'PT-2008', 'PT-2009', 'PT-2010', 
    'PT-2011'
  ],
  'name': [
    'Anthony Ramirez', 'anthony ramirez', 'Grace Mitchell', 'Daniel Brooks', 
    'Nina Patel', 'Marcus Johnson', 'Elena Cruz', 'elena cruz', 
    'William Carter', 'Sophia Nguyen', None, 'Sophia Nguyen', 
    'Ethan Walker'
  ],
  'age': [
    '52', '52', 34, '28', 
    '61', 47, '26', 26, 
    '73', '39', 44, '39', 
    '58'
  ],
  'department': [
    'ER', 'er', 'Trauma', 'ER', 
    'Cardiology', 'Trauma', 'ER', 'er', 
    'ICU', 'ER', 'ER', 'ER', 
    'ICU'
  ],
  'triage_level': [
    'Critical', 'critical', 'Moderate', 'HIGH', 
    'Low', 'Moderate', 'critical', 'CRITICAL', 
    'High', 'Low', 'Moderate', 'low', 
    None
  ],
  'wait_time_minutes': [
    '12', '12', 55, '40 mins', 
    140, 60, '8', 8, 
    '95', '25', None, '25', 
    '70'
  ],
  'admitted': [
    True, True, False, True, 
    True, False, True, True, 
    False, True, False, True, 
    None
  ]
})

In [45]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,PT-2001,Anthony Ramirez,52,ER,Critical,12,True
1,PT-2001,anthony ramirez,52,er,critical,12,True
2,PT-2002,Grace Mitchell,34,Trauma,Moderate,55,False
3,PT-2003,Daniel Brooks,28,ER,HIGH,40 mins,True
4,PT-2004,Nina Patel,61,Cardiology,Low,140,True
5,PT-2005,Marcus Johnson,47,Trauma,Moderate,60,False
6,PT-2006,Elena Cruz,26,ER,critical,8,True
7,PT-2006,elena cruz,26,er,CRITICAL,8,True
8,PT-2007,William Carter,73,ICU,High,95,False
9,PT-2008,Sophia Nguyen,39,ER,Low,25,True
10,PT-2009,None,44,ER,Moderate,None,False
11,PT-2010,Sophia Nguyen,39,ER,low,25,True
12,PT-2011,Ethan Walker,58,ICU,None,70,None

In [46]:
patients = patients.drop_duplicates()

In [47]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,PT-2001,Anthony Ramirez,52,ER,Critical,12,True
1,PT-2001,anthony ramirez,52,er,critical,12,True
2,PT-2002,Grace Mitchell,34,Trauma,Moderate,55,False
3,PT-2003,Daniel Brooks,28,ER,HIGH,40 mins,True
4,PT-2004,Nina Patel,61,Cardiology,Low,140,True
5,PT-2005,Marcus Johnson,47,Trauma,Moderate,60,False
6,PT-2006,Elena Cruz,26,ER,critical,8,True
7,PT-2006,elena cruz,26,er,CRITICAL,8,True
8,PT-2007,William Carter,73,ICU,High,95,False
9,PT-2008,Sophia Nguyen,39,ER,Low,25,True
10,PT-2009,None,44,ER,Moderate,None,False
11,PT-2010,Sophia Nguyen,39,ER,low,25,True
12,PT-2011,Ethan Walker,58,ICU,None,70,None

In [48]:
patients = patients.apply(lambda x: x.str.lower() if x.dtype == 'object' and x.dropna().apply(type).eq(str).all() else x)

In [49]:
patients = patients.drop_duplicates()

In [50]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12,True
2,pt-2002,grace mitchell,34,trauma,moderate,55,False
3,pt-2003,daniel brooks,28,er,high,40 mins,True
4,pt-2004,nina patel,61,cardiology,low,140,True
5,pt-2005,marcus johnson,47,trauma,moderate,60,False
6,pt-2006,elena cruz,26,er,critical,8,True
7,pt-2006,elena cruz,26,er,critical,8,True
8,pt-2007,william carter,73,icu,high,95,False
9,pt-2008,sophia nguyen,39,er,low,25,True
10,pt-2009,None,44,er,moderate,None,False
11,pt-2010,sophia nguyen,39,er,low,25,True
12,pt-2011,ethan walker,58,icu,None,70,None

In [51]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 12
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         12 non-null     object
 1   name               11 non-null     object
 2   age                12 non-null     object
 3   department         12 non-null     object
 4   triage_level       11 non-null     object
 5   wait_time_minutes  11 non-null     object
 6   admitted           11 non-null     object
dtypes: object(7)
memory usage: 768.0+ bytes

In [52]:
patients['age'] = pd.to_numeric(patients['age'])

In [53]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12,True
2,pt-2002,grace mitchell,34,trauma,moderate,55,False
3,pt-2003,daniel brooks,28,er,high,40 mins,True
4,pt-2004,nina patel,61,cardiology,low,140,True
5,pt-2005,marcus johnson,47,trauma,moderate,60,False
6,pt-2006,elena cruz,26,er,critical,8,True
7,pt-2006,elena cruz,26,er,critical,8,True
8,pt-2007,william carter,73,icu,high,95,False
9,pt-2008,sophia nguyen,39,er,low,25,True
10,pt-2009,None,44,er,moderate,None,False
11,pt-2010,sophia nguyen,39,er,low,25,True
12,pt-2011,ethan walker,58,icu,None,70,None

In [54]:
patients = patients.drop_duplicates()

In [55]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12,True
2,pt-2002,grace mitchell,34,trauma,moderate,55,False
3,pt-2003,daniel brooks,28,er,high,40 mins,True
4,pt-2004,nina patel,61,cardiology,low,140,True
5,pt-2005,marcus johnson,47,trauma,moderate,60,False
6,pt-2006,elena cruz,26,er,critical,8,True
7,pt-2006,elena cruz,26,er,critical,8,True
8,pt-2007,william carter,73,icu,high,95,False
9,pt-2008,sophia nguyen,39,er,low,25,True
10,pt-2009,None,44,er,moderate,None,False
11,pt-2010,sophia nguyen,39,er,low,25,True
12,pt-2011,ethan walker,58,icu,None,70,None

In [58]:

patients.loc[3, 'wait_time_minutes'] = 40

In [59]:
patients['wait_time_minutes'] = pd.to_numeric(patients['wait_time_minutes'])

In [60]:
patients = patients.drop_duplicates()

In [61]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12.0,True
2,pt-2002,grace mitchell,34,trauma,moderate,55.0,False
3,pt-2003,daniel brooks,28,er,high,40.0,True
4,pt-2004,nina patel,61,cardiology,low,140.0,True
5,pt-2005,marcus johnson,47,trauma,moderate,60.0,False
6,pt-2006,elena cruz,26,er,critical,8.0,True
8,pt-2007,william carter,73,icu,high,95.0,False
9,pt-2008,sophia nguyen,39,er,low,25.0,True
10,pt-2009,None,44,er,moderate,NaN,False
11,pt-2010,sophia nguyen,39,er,low,25.0,True
12,pt-2011,ethan walker,58,icu,None,70.0,None

In [62]:
patients = patients.drop(11)

In [63]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12.0,True
2,pt-2002,grace mitchell,34,trauma,moderate,55.0,False
3,pt-2003,daniel brooks,28,er,high,40.0,True
4,pt-2004,nina patel,61,cardiology,low,140.0,True
5,pt-2005,marcus johnson,47,trauma,moderate,60.0,False
6,pt-2006,elena cruz,26,er,critical,8.0,True
8,pt-2007,william carter,73,icu,high,95.0,False
9,pt-2008,sophia nguyen,39,er,low,25.0,True
10,pt-2009,None,44,er,moderate,NaN,False
12,pt-2011,ethan walker,58,icu,None,70.0,None

In [64]:
patients['name'] = patients['name'].fillna('Unknown')

In [65]:
patients['triage_level'] = patients['triage_level'].fillna(patients['triage_level'].mode()[0])

In [66]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12.0,True
2,pt-2002,grace mitchell,34,trauma,moderate,55.0,False
3,pt-2003,daniel brooks,28,er,high,40.0,True
4,pt-2004,nina patel,61,cardiology,low,140.0,True
5,pt-2005,marcus johnson,47,trauma,moderate,60.0,False
6,pt-2006,elena cruz,26,er,critical,8.0,True
8,pt-2007,william carter,73,icu,high,95.0,False
9,pt-2008,sophia nguyen,39,er,low,25.0,True
10,pt-2009,Unknown,44,er,moderate,NaN,False
12,pt-2011,ethan walker,58,icu,moderate,70.0,None

In [67]:
patients['wait_time_minutes'] = patients['wait_time_minutes'].fillna(patients['wait_time_minutes'].median())

In [69]:
patients['admitted'] = patients['admitted'].fillna(False)

In [70]:
patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,pt-2001,anthony ramirez,52,er,critical,12.0,True
2,pt-2002,grace mitchell,34,trauma,moderate,55.0,False
3,pt-2003,daniel brooks,28,er,high,40.0,True
4,pt-2004,nina patel,61,cardiology,low,140.0,True
5,pt-2005,marcus johnson,47,trauma,moderate,60.0,False
6,pt-2006,elena cruz,26,er,critical,8.0,True
8,pt-2007,william carter,73,icu,high,95.0,False
9,pt-2008,sophia nguyen,39,er,low,25.0,True
10,pt-2009,Unknown,44,er,moderate,55.0,False
12,pt-2011,ethan walker,58,icu,moderate,70.0,False