Instructions
Here's the same DataFrame named characters containing different D&D heroes.

Create the following DataFrames:

high_level that contains all characters that are above level 5.
halfling_bards that contains all characters whose race is 'Halfling' AND whose class is 'Bard'.
magic_users that contains all characters whose class is Wizard OR Sorcerer OR Warlock.
As you work on these prompts, make sure to display your new DataFrames to confirm you've done the filtering correctly.

In [1]:
import pandas as pd

In [2]:
# D&D characters data
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}

In [4]:
characters = pd.DataFrame(characters_data)

In [5]:
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [7]:
high_level = characters[characters['level']>5]

In [8]:
high_level

   name        race    class  level  hp       alignment
4   Nyx    Tiefling    Rogue      6  48    Chaotic Evil
5  Kael  Dragonborn  Paladin      7  56  Lawful Neutral

In [9]:
characters['level']>5

0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9    False
Name: level, dtype: bool

In [14]:
halfing_bards = characters[(characters['race'] == 'Halfling') & (characters['class'] == 'Bard')]

In [15]:
halfing_bards

   name      race class  level  hp     alignment
6  Mira  Halfling  Bard      3  30  Neutral Good

In [17]:
magic_users = characters[(characters['class']=='Wizard') | (characters['class']=='Sorcerer') | (characters['class']=='Warlock')]

In [18]:
magic_users

      name     race     class  level  hp     alignment
2     Glim    Gnome    Wizard      4  33       Neutral
8     Zara  Aasimar  Sorcerer      4  36  Chaotic Good
9  Fenwick   Goblin   Warlock      2  24   Lawful Evil