Instructions
It's time to let your creativity shine!

Create a DataFrame about a topic of your choice! It should have at least 10 rows × 5 columns.

Once it is created, perform the following operations:

Add a new column
Sort the DataFrame by a particular column
Filter out rows based on one or more conditions
If you're having trouble thinking of topics, here are some ideas to get you started:

Statistics about your favorite sports team
Data about your favorite movies, books, video games, or music
Information about your friends and family
Note: If you need help creating your dataset, feel free to use ChatGPT or another AI tool to get you started. We found the following prompt helped create a good starting DataFrame:

Give me code to create a DataFrame about [your topic] with 10+ rows and 5+ columns. Some of the columns should be about [X, Y, Z].

In [31]:
import pandas as pd

In [32]:
data = {
    'player': ['Messi', 'Ronaldo', 'Neymar', 'Mbappe', 'Salah', 'Kane', 'Benzema', 'De Bruyne', 'Modric', 'Lewandowski'],
    'country': ['Argentina', 'Portugal', 'Brazil', 'France', 'Egypt', 'England', 'France', 'Belgium', 'Croatia', 'Poland'],
    'goals': [45, 50, 30, 40, 35, 28, 38, 12, 10, 48],
    'assists': [20, 15, 25, 18, 12, 10, 14, 30, 22, 16],
    'age': [36, 38, 31, 24, 31, 30, 35, 32, 38, 35]
}

In [33]:
player = pd.DataFrame(data)

In [34]:
player

        player    country  goals  assists  age
0        Messi  Argentina     45       20   36
1      Ronaldo   Portugal     50       15   38
2       Neymar     Brazil     30       25   31
3       Mbappe     France     40       18   24
4        Salah      Egypt     35       12   31
5         Kane    England     28       10   30
6      Benzema     France     38       14   35
7    De Bruyne    Belgium     12       30   32
8       Modric    Croatia     10       22   38
9  Lewandowski     Poland     48       16   35

In [35]:
player['matches_played'] = [850, 900, 780, 420, 650, 580, 720, 680, 750, 810]

In [36]:
player

        player    country  goals  assists  age  matches_played
0        Messi  Argentina     45       20   36             850
1      Ronaldo   Portugal     50       15   38             900
2       Neymar     Brazil     30       25   31             780
3       Mbappe     France     40       18   24             420
4        Salah      Egypt     35       12   31             650
5         Kane    England     28       10   30             580
6      Benzema     France     38       14   35             720
7    De Bruyne    Belgium     12       30   32             680
8       Modric    Croatia     10       22   38             750
9  Lewandowski     Poland     48       16   35             810

In [37]:
player = player.sort_values(by='goals', ascending=False)

In [38]:
player

        player    country  goals  assists  age  matches_played
1      Ronaldo   Portugal     50       15   38             900
9  Lewandowski     Poland     48       16   35             810
0        Messi  Argentina     45       20   36             850
3       Mbappe     France     40       18   24             420
6      Benzema     France     38       14   35             720
4        Salah      Egypt     35       12   31             650
2       Neymar     Brazil     30       25   31             780
5         Kane    England     28       10   30             580
7    De Bruyne    Belgium     12       30   32             680
8       Modric    Croatia     10       22   38             750

In [39]:
player = player[((player['age']>25) & (player['age']<36)) & ((player['assists']>20) | (player['assists']<15))]

In [40]:
player

      player  country  goals  assists  age  matches_played
6    Benzema   France     38       14   35             720
4      Salah    Egypt     35       12   31             650
2     Neymar   Brazil     30       25   31             780
5       Kane  England     28       10   30             580
7  De Bruyne  Belgium     12       30   32             680