Instructions
In the notebook on the right, we've imported pandas and created a movies DataFrame!

Now, type the following into the input box at the bottom of the page:

movies

And press shift + enter to run the code. A table should appear.

Boom. We're now ready to learn how to use Pandas to answer questions about this data. 🙌

Bonus: Now let’s get curious. What’s a question you might ask about this dataset?

Write it as a Python comment and hit shift + enter again. For example:

# What month is the best month to release a movie? What month is the worst?
# Which film studio has the highest average profit?

In [1]:
import pandas as pd

# Recent Oscar winners
movie_data = {
  'title': ['Parasite', 'Nomadland', 'CODA', 'Everything Everywhere All at Once', 'Oppenheimer', 'Anora'],
  'release_date': ['2019-05-30', '2020-09-11', '2021-01-28', '2022-03-11', '2023-07-21', '2024-05-24'],
  'genre': ['Thriller', 'Drama', 'Drama',  'Action', 'Biography', 'Drama'],
  'studio': ['CJ Entertainment', 'Searchlight Pictures', 'Apple TV+', 'A24', 'Universal Pictures', 'A24'],
  'budget': [11400000, 5000000, 10000000, 25000000, 100000000, 3000000],
  'box_office': [263000000, 39000000, 1900000, 143000000, 975000000, 57000000],
  'runtime_minutes': [132, 108, 111, 139, 180, 98],
  'rating': [8.5, 7.3, 8.0, 8.0, 8.6, 8.1]
}

# Create the DataFrame
movies = pd.DataFrame(movie_data)

In [2]:
movies

,title,release_date,genre,studio,budget,box_office,runtime_minutes,rating
0,Parasite,2019-05-30,Thriller,CJ Entertainment,11400000,263000000,132,8.5
1,Nomadland,2020-09-11,Drama,Searchlight Pictures,5000000,39000000,108,7.3
2,CODA,2021-01-28,Drama,Apple TV+,10000000,1900000,111,8.0
3,Everything Everywhere All at Once,2022-03-11,Action,A24,25000000,143000000,139,8.0
4,Oppenheimer,2023-07-21,Biography,Universal Pictures,100000000,975000000,180,8.6
5,Anora,2024-05-24,Drama,A24,3000000,57000000,98,8.1

In [3]:
print(movies['release_date'][round(movies['box_office']/movies['budget'],2).idxmax()])

2019-05-30

In [4]:
pd.to_datetime(movies['release_date'][0])

Timestamp('2019-05-30 00:00:00')

In [5]:
movies.groupby('studio')['box_office'].apply(list)

studio
A24                     [143000000, 57000000]
Apple TV+                           [1900000]
CJ Entertainment                  [263000000]
Searchlight Pictures               [39000000]
Universal Pictures                [975000000]
Name: box_office, dtype: object

In [6]:
movies.groupby('studio')['box_office'].mean()

studio
A24                     100000000.0
Apple TV+                 1900000.0
CJ Entertainment        263000000.0
Searchlight Pictures     39000000.0
Universal Pictures      975000000.0
Name: box_office, dtype: float64

In [7]:
print((movies.groupby('studio')['box_office'].mean()).idxmax())

Universal Pictures

In [8]:
movies

,title,release_date,genre,studio,budget,box_office,runtime_minutes,rating
0,Parasite,2019-05-30,Thriller,CJ Entertainment,11400000,263000000,132,8.5
1,Nomadland,2020-09-11,Drama,Searchlight Pictures,5000000,39000000,108,7.3
2,CODA,2021-01-28,Drama,Apple TV+,10000000,1900000,111,8.0
3,Everything Everywhere All at Once,2022-03-11,Action,A24,25000000,143000000,139,8.0
4,Oppenheimer,2023-07-21,Biography,Universal Pictures,100000000,975000000,180,8.6
5,Anora,2024-05-24,Drama,A24,3000000,57000000,98,8.1

In [9]:
print(movies['studio'][(movies['box_office']/movies['budget']).idxmax()])

CJ Entertainment

In [10]:
print(movies['rating'].mean())

8.083333333333334

In [11]:
print(movies['studio'][(movies['box_office']/movies['budget']).idxmax()])
if movies[movies['studio']==movies['studio'][(movies['box_office']/movies['budget']).idxmax()]]['rating'].item() > movies['rating'].mean():
    print("rating is above average rating")
else:
    print("rating is below average rating")

CJ Entertainment
rating is above average rating

In [12]:
movies[movies['studio']==movies['studio'][(movies['box_office']/movies['budget']).idxmax()]]['rating']

0    8.5
Name: rating, dtype: float64

In [13]:
print((movies['studio'][(movies['box_office']/movies['budget']).idxmax()])+",", ("yes") if movies[movies['studio']==movies['studio'][(movies['box_office']/movies['budget']).idxmax()]]['rating'].item() > movies['rating'].mean() else print("no"))

CJ Entertainment, yes